[package]
name = "ep2conllu"
version = "0.1.0"
edition = "2018"
authors = ["DanieÌˆl de Kok <me@danieldk.eu>"]

[dependencies]
conllx = "0.9"
flate2 = "0.2"
getopts = "0.2"
stdinout = "0.4"
thiserror = "1"
xml-rs = "0.7"
